from setuptools import setup, find_packages

setup(
    name="easyrec-extended",
    version="0.1.0",
    description="Extended EasyRec framework with Policy-driven recommendation engine",
    author="IdeaX Business",
    author_email="dev@ideax-business.com",
    url="https://github.com/ideax-business/EasyRec-Extended",
    packages=find_packages(),
    python_requires=">=3.7",
    install_requires=[
        "Flask>=2.3.0",
        "requests>=2.31.0",
        "tensorflow>=2.5.0",
        "protobuf>=3.19.0",
        "numpy>=1.19.0",
        "pandas>=1.1.0",
        "scipy>=1.10.0",
        "scikit-learn>=1.3.0",
        "xgboost>=2.0.0",
        "lightgbm>=4.0.0",
        "redis>=5.0.0",
        "python-json-logger>=2.0.7",
        "prometheus-client>=0.17.0",
        "python-dotenv>=1.0.0",
        "pyyaml>=6.0.1",
        "grpcio>=1.40.0",
        "grpcio-tools>=1.40.0",
    ],
    extras_require={
        "dev": [
            "pytest>=6.2.0",
            "pytest-cov>=4.1.0",
            "black>=21.0",
            "pylint>=2.17.0",
            "mypy>=1.5.0",
        ],
        "ann": [
            "faiss-cpu>=1.7.0",
        ],
    },
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
    ],
)
