# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from serving import recommendation_pb2 as recommendation__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in recommendation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RecommendServiceStub(object):
    """── Service ──────────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Recommend = channel.unary_unary(
                '/recommendation.RecommendService/Recommend',
                request_serializer=recommendation__pb2.RecommendRequest.SerializeToString,
                response_deserializer=recommendation__pb2.RecommendResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/recommendation.RecommendService/HealthCheck',
                request_serializer=recommendation__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=recommendation__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.ListModels = channel.unary_unary(
                '/recommendation.RecommendService/ListModels',
                request_serializer=recommendation__pb2.ListModelsRequest.SerializeToString,
                response_deserializer=recommendation__pb2.ListModelsResponse.FromString,
                _registered_method=True)
        self.ReloadModel = channel.unary_unary(
                '/recommendation.RecommendService/ReloadModel',
                request_serializer=recommendation__pb2.ReloadModelRequest.SerializeToString,
                response_deserializer=recommendation__pb2.ReloadModelResponse.FromString,
                _registered_method=True)


class RecommendServiceServicer(object):
    """── Service ──────────────────────────────────────────────────────────────────

    """

    def Recommend(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReloadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecommendServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Recommend': grpc.unary_unary_rpc_method_handler(
                    servicer.Recommend,
                    request_deserializer=recommendation__pb2.RecommendRequest.FromString,
                    response_serializer=recommendation__pb2.RecommendResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=recommendation__pb2.HealthCheckRequest.FromString,
                    response_serializer=recommendation__pb2.HealthCheckResponse.SerializeToString,
            ),
            'ListModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ListModels,
                    request_deserializer=recommendation__pb2.ListModelsRequest.FromString,
                    response_serializer=recommendation__pb2.ListModelsResponse.SerializeToString,
            ),
            'ReloadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.ReloadModel,
                    request_deserializer=recommendation__pb2.ReloadModelRequest.FromString,
                    response_serializer=recommendation__pb2.ReloadModelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'recommendation.RecommendService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('recommendation.RecommendService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RecommendService(object):
    """── Service ──────────────────────────────────────────────────────────────────

    """

    @staticmethod
    def Recommend(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.RecommendService/Recommend',
            recommendation__pb2.RecommendRequest.SerializeToString,
            recommendation__pb2.RecommendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.RecommendService/HealthCheck',
            recommendation__pb2.HealthCheckRequest.SerializeToString,
            recommendation__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.RecommendService/ListModels',
            recommendation__pb2.ListModelsRequest.SerializeToString,
            recommendation__pb2.ListModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReloadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/recommendation.RecommendService/ReloadModel',
            recommendation__pb2.ReloadModelRequest.SerializeToString,
            recommendation__pb2.ReloadModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
